
name: deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known_hosts
        run: |
          ssh-keyscan -H srv1501506.hstgr.cloud >> ~/.ssh/known_hosts

      - name: Deploy to prod server
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd /root/JewelleryStore && \
            git pull origin main && \
            php bin/console cache:clear --env=prod && \
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod &&\
            systemctl restart messenger-worker \
          "
