
name: deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan -H srv1501506.hstgr.cloud >> ~/.ssh/known_hosts

      - name: Deploy to prod server
        run: |
          ssh root@srv1501506.hstgr.cloud "\
            cd /root/JewelleryStore && \
            git pull origin main && \
            php bin/console cache:clear --env=prod && \
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod &&\
            systemctl restart messenger-worker \
          "
 